---
- name: CloudForms Automate Method Conversion
  hosts: localhost
  vars:
    provider_url: 'https://192.168.150.77/api/providers'
    tenant_url: 'https://192.168.150.77/api/tenants'
    network_url: 'https://192.168.150.77/api/cloud_networks'
    tenant_category: 'tenant'
  tasks:
    - name: Get provider details
      uri:
        url: "{{ provider_url }}"
        method: GET
        user: 'admin'
        password: 'admin'
        force_basic_auth: yes
        status_code: 200
      register: provider_result

    - name: Get tenant details
      uri:
        url: "{{ tenant_url }}"
        method: GET
        user: 'admin'
        password: 'admin'
        force_basic_auth: yes
        status_code: 200
      register: tenant_result

    - name: Get cloud network details
      uri:
        url: "{{ network_url }}"
        method: GET
        user: 'admin'
        password: 'admin'
        force_basic_auth: yes
        status_code: 200
      register: network_result

    - name: Build dialog hash
      set_fact:
        dialog_hash: >
          {%- set dh = {} -%}
          {%- for network in network_result.json.resources -%}
            {%- set _ = dh.update({network.id: network.name}) -%}
          {%- endfor -%}
          {{ dh }}
      
    - name: Display dialog hash
      debug:
        var: dialog_hash
